import { Inter } from "next/font/google";
import "./globals.css";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import Custom404 from "./error";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ErrorBoundary fallback={<Custom404 />}>{children}</ErrorBoundary>
      </body>
    </html>
  );
}
// nftwHBt793nKPFh4
// GPm9VcZGw8VJUfxK    -mongodb atlas password
// zHe1IanNZC5WFsizLvQ1uwRIzYlDg6Bp3XLYiZTc849s8tE3LEprdXPptRndbGz2  -monodb api key
